# Generated by Django 4.2 on 2023-04-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chi_api', '0002_alter_customer_table_alter_employee_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='milage',
            new_name='mileage',
        ),
    ]
