# Generated by Django 4.0.5 on 2023-04-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chi_api', '0003_rename_milage_vehicle_mileage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='VehicleTransaction',
        ),
    ]
