# Generated by Django 4.0.5 on 2023-04-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chi_api', '0005_alter_vehicletransaction_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicletransaction',
            old_name='transaction_id',
            new_name='vehicle_transaction_id',
        ),
    ]
