# Generated by Django 4.2 on 2023-04-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chi_api', '0006_rename_transaction_id_vehicletransaction_vehicle_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
